### ISSUE TITLE
지원자 정보 상세 보기 api 응답값 오류

### ISSUE THREAD

**Issue by DongramO** [Freemd-it/RecruitingAdmin#14]
![image](https://user-images.githubusercontent.com/31988552/52389272-fba7f580-2ad5-11e9-8648-37cdc37d469a.png)

비어있는 데이터에 대하여, 객체인 경우 빈객체, 배열인 경우 빈 배열을 넘겨주세요.

**Comment by urbanscenery** [comment]
8749893025edb230c1069290663b66a854bf19f1
지원상태 201 이상의 지원자만 불러오게 하는것으로 해결(미지원상태의 지원자만 비어있는 데이터 존재)
