### ISSUE TITLE
질문 수정하기 업데이트 쿼리 애러

### ISSUE THREAD

**Issue by DongramO** [Freemd-it/RecruitingAdmin#15]
![image](https://user-images.githubusercontent.com/31988552/52402766-74c04080-2b08-11e9-8aaa-4b1a98b90945.png)

클라이언트에서 전송한 데이터는 정상적으로 넘어오나
서버에서 데이터를 받은후 쿼리 작동하는 부분에서 오류 발생

**Comment by DongramO** [comment]
정확히는 팀을 수정한 경우에 팀 번호가 안바뀜

**Comment by urbanscenery** [comment]
Commit : 7172edc06b63c4146266038bfd6082a214bc2aa6
팀수정도 가능하게 변경.

**Comment by urbanscenery** [comment]
Commit : 5a681226e928fcf2cbfa40822d14ddde353f58ee
여기서 질문 등록 및 수정할 때 string으로 된 본부 및 팀 정보도 들어가게 수정.
